// logstreamer.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v4.25.3
// source: proto/logstreamer.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LogLine_Level int32

const (
	LogLine_STDOUT LogLine_Level = 0
	LogLine_STDERR LogLine_Level = 1
)

// Enum value maps for LogLine_Level.
var (
	LogLine_Level_name = map[int32]string{
		0: "STDOUT",
		1: "STDERR",
	}
	LogLine_Level_value = map[string]int32{
		"STDOUT": 0,
		"STDERR": 1,
	}
)

func (x LogLine_Level) Enum() *LogLine_Level {
	p := new(LogLine_Level)
	*p = x
	return p
}

func (x LogLine_Level) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LogLine_Level) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_logstreamer_proto_enumTypes[0].Descriptor()
}

func (LogLine_Level) Type() protoreflect.EnumType {
	return &file_proto_logstreamer_proto_enumTypes[0]
}

func (x LogLine_Level) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LogLine_Level.Descriptor instead.
func (LogLine_Level) EnumDescriptor() ([]byte, []int) {
	return file_proto_logstreamer_proto_rawDescGZIP(), []int{4, 0}
}

// Message from client to server
type StreamLogRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Event:
	//
	//	*StreamLogRequest_Metadata
	//	*StreamLogRequest_Line
	//	*StreamLogRequest_Completion
	Event         isStreamLogRequest_Event `protobuf_oneof:"event"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamLogRequest) Reset() {
	*x = StreamLogRequest{}
	mi := &file_proto_logstreamer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamLogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamLogRequest) ProtoMessage() {}

func (x *StreamLogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_logstreamer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamLogRequest.ProtoReflect.Descriptor instead.
func (*StreamLogRequest) Descriptor() ([]byte, []int) {
	return file_proto_logstreamer_proto_rawDescGZIP(), []int{0}
}

func (x *StreamLogRequest) GetEvent() isStreamLogRequest_Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *StreamLogRequest) GetMetadata() *StreamMetadata {
	if x != nil {
		if x, ok := x.Event.(*StreamLogRequest_Metadata); ok {
			return x.Metadata
		}
	}
	return nil
}

func (x *StreamLogRequest) GetLine() *LogLine {
	if x != nil {
		if x, ok := x.Event.(*StreamLogRequest_Line); ok {
			return x.Line
		}
	}
	return nil
}

func (x *StreamLogRequest) GetCompletion() *StreamCompletion {
	if x != nil {
		if x, ok := x.Event.(*StreamLogRequest_Completion); ok {
			return x.Completion
		}
	}
	return nil
}

type isStreamLogRequest_Event interface {
	isStreamLogRequest_Event()
}

type StreamLogRequest_Metadata struct {
	// Must be the first message sent by the client.
	Metadata *StreamMetadata `protobuf:"bytes,1,opt,name=metadata,proto3,oneof"`
}

type StreamLogRequest_Line struct {
	// Subsequent log lines.
	Line *LogLine `protobuf:"bytes,2,opt,name=line,proto3,oneof"`
}

type StreamLogRequest_Completion struct {
	// Sent by the client (in 'run' mode) when the command finishes.
	Completion *StreamCompletion `protobuf:"bytes,3,opt,name=completion,proto3,oneof"`
}

func (*StreamLogRequest_Metadata) isStreamLogRequest_Event() {}

func (*StreamLogRequest_Line) isStreamLogRequest_Event() {}

func (*StreamLogRequest_Completion) isStreamLogRequest_Event() {}

// Completion message sent by the client.
type StreamCompletion struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExitCode      int32                  `protobuf:"varint,1,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"` // The captured exit code of the script.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamCompletion) Reset() {
	*x = StreamCompletion{}
	mi := &file_proto_logstreamer_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamCompletion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamCompletion) ProtoMessage() {}

func (x *StreamCompletion) ProtoReflect() protoreflect.Message {
	mi := &file_proto_logstreamer_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamCompletion.ProtoReflect.Descriptor instead.
func (*StreamCompletion) Descriptor() ([]byte, []int) {
	return file_proto_logstreamer_proto_rawDescGZIP(), []int{1}
}

func (x *StreamCompletion) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

// Message from server to client
type StreamLogResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Event:
	//
	//	*StreamLogResponse_Started
	//	*StreamLogResponse_Error
	Event         isStreamLogResponse_Event `protobuf_oneof:"event"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamLogResponse) Reset() {
	*x = StreamLogResponse{}
	mi := &file_proto_logstreamer_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamLogResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamLogResponse) ProtoMessage() {}

func (x *StreamLogResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_logstreamer_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamLogResponse.ProtoReflect.Descriptor instead.
func (*StreamLogResponse) Descriptor() ([]byte, []int) {
	return file_proto_logstreamer_proto_rawDescGZIP(), []int{2}
}

func (x *StreamLogResponse) GetEvent() isStreamLogResponse_Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *StreamLogResponse) GetStarted() *StreamStarted {
	if x != nil {
		if x, ok := x.Event.(*StreamLogResponse_Started); ok {
			return x.Started
		}
	}
	return nil
}

func (x *StreamLogResponse) GetError() string {
	if x != nil {
		if x, ok := x.Event.(*StreamLogResponse_Error); ok {
			return x.Error
		}
	}
	return ""
}

type isStreamLogResponse_Event interface {
	isStreamLogResponse_Event()
}

type StreamLogResponse_Started struct {
	// The first response from the server after creating the run.
	Started *StreamStarted `protobuf:"bytes,1,opt,name=started,proto3,oneof"`
}

type StreamLogResponse_Error struct {
	// For future use (e.g., server-side errors).
	Error string `protobuf:"bytes,2,opt,name=error,proto3,oneof"`
}

func (*StreamLogResponse_Started) isStreamLogResponse_Event() {}

func (*StreamLogResponse_Error) isStreamLogResponse_Event() {}

// Metadata sent by the client.
type StreamMetadata struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// If provided, this project name is used. If not, the server
	// may associate the run with a default project based on the API Token.
	ProjectName   string `protobuf:"bytes,1,opt,name=project_name,json=projectName,proto3" json:"project_name,omitempty"`
	GroupName     string `protobuf:"bytes,2,opt,name=group_name,json=groupName,proto3" json:"group_name,omitempty"` // The group name for the run.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamMetadata) Reset() {
	*x = StreamMetadata{}
	mi := &file_proto_logstreamer_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamMetadata) ProtoMessage() {}

func (x *StreamMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_proto_logstreamer_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamMetadata.ProtoReflect.Descriptor instead.
func (*StreamMetadata) Descriptor() ([]byte, []int) {
	return file_proto_logstreamer_proto_rawDescGZIP(), []int{3}
}

func (x *StreamMetadata) GetProjectName() string {
	if x != nil {
		return x.ProjectName
	}
	return ""
}

func (x *StreamMetadata) GetGroupName() string {
	if x != nil {
		return x.GroupName
	}
	return ""
}

// A single log line sent by the client.
type LogLine struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Level         LogLine_Level          `protobuf:"varint,2,opt,name=level,proto3,enum=swiftlog.v1.LogLine_Level" json:"level,omitempty"`
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogLine) Reset() {
	*x = LogLine{}
	mi := &file_proto_logstreamer_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogLine) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogLine) ProtoMessage() {}

func (x *LogLine) ProtoReflect() protoreflect.Message {
	mi := &file_proto_logstreamer_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogLine.ProtoReflect.Descriptor instead.
func (*LogLine) Descriptor() ([]byte, []int) {
	return file_proto_logstreamer_proto_rawDescGZIP(), []int{4}
}

func (x *LogLine) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *LogLine) GetLevel() LogLine_Level {
	if x != nil {
		return x.Level
	}
	return LogLine_STDOUT
}

func (x *LogLine) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

// Server confirmation that the stream has been initiated.
type StreamStarted struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RunId         string                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"` // The unique ID for this run.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamStarted) Reset() {
	*x = StreamStarted{}
	mi := &file_proto_logstreamer_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamStarted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamStarted) ProtoMessage() {}

func (x *StreamStarted) ProtoReflect() protoreflect.Message {
	mi := &file_proto_logstreamer_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamStarted.ProtoReflect.Descriptor instead.
func (*StreamStarted) Descriptor() ([]byte, []int) {
	return file_proto_logstreamer_proto_rawDescGZIP(), []int{5}
}

func (x *StreamStarted) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

var File_proto_logstreamer_proto protoreflect.FileDescriptor

const file_proto_logstreamer_proto_rawDesc = "" +
	"\n" +
	"\x17proto/logstreamer.proto\x12\vswiftlog.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xc3\x01\n" +
	"\x10StreamLogRequest\x129\n" +
	"\bmetadata\x18\x01 \x01(\v2\x1b.swiftlog.v1.StreamMetadataH\x00R\bmetadata\x12*\n" +
	"\x04line\x18\x02 \x01(\v2\x14.swiftlog.v1.LogLineH\x00R\x04line\x12?\n" +
	"\n" +
	"completion\x18\x03 \x01(\v2\x1d.swiftlog.v1.StreamCompletionH\x00R\n" +
	"completionB\a\n" +
	"\x05event\"/\n" +
	"\x10StreamCompletion\x12\x1b\n" +
	"\texit_code\x18\x01 \x01(\x05R\bexitCode\"l\n" +
	"\x11StreamLogResponse\x126\n" +
	"\astarted\x18\x01 \x01(\v2\x1a.swiftlog.v1.StreamStartedH\x00R\astarted\x12\x16\n" +
	"\x05error\x18\x02 \x01(\tH\x00R\x05errorB\a\n" +
	"\x05event\"R\n" +
	"\x0eStreamMetadata\x12!\n" +
	"\fproject_name\x18\x01 \x01(\tR\vprojectName\x12\x1d\n" +
	"\n" +
	"group_name\x18\x02 \x01(\tR\tgroupName\"\xb0\x01\n" +
	"\aLogLine\x128\n" +
	"\ttimestamp\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x120\n" +
	"\x05level\x18\x02 \x01(\x0e2\x1a.swiftlog.v1.LogLine.LevelR\x05level\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\"\x1f\n" +
	"\x05Level\x12\n" +
	"\n" +
	"\x06STDOUT\x10\x00\x12\n" +
	"\n" +
	"\x06STDERR\x10\x01\"&\n" +
	"\rStreamStarted\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId2]\n" +
	"\vLogStreamer\x12N\n" +
	"\tStreamLog\x12\x1d.swiftlog.v1.StreamLogRequest\x1a\x1e.swiftlog.v1.StreamLogResponse(\x010\x01B'Z%github.com/aliancn/swiftlog/cli/protob\x06proto3"

var (
	file_proto_logstreamer_proto_rawDescOnce sync.Once
	file_proto_logstreamer_proto_rawDescData []byte
)

func file_proto_logstreamer_proto_rawDescGZIP() []byte {
	file_proto_logstreamer_proto_rawDescOnce.Do(func() {
		file_proto_logstreamer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_logstreamer_proto_rawDesc), len(file_proto_logstreamer_proto_rawDesc)))
	})
	return file_proto_logstreamer_proto_rawDescData
}

var file_proto_logstreamer_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_logstreamer_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_logstreamer_proto_goTypes = []any{
	(LogLine_Level)(0),            // 0: swiftlog.v1.LogLine.Level
	(*StreamLogRequest)(nil),      // 1: swiftlog.v1.StreamLogRequest
	(*StreamCompletion)(nil),      // 2: swiftlog.v1.StreamCompletion
	(*StreamLogResponse)(nil),     // 3: swiftlog.v1.StreamLogResponse
	(*StreamMetadata)(nil),        // 4: swiftlog.v1.StreamMetadata
	(*LogLine)(nil),               // 5: swiftlog.v1.LogLine
	(*StreamStarted)(nil),         // 6: swiftlog.v1.StreamStarted
	(*timestamppb.Timestamp)(nil), // 7: google.protobuf.Timestamp
}
var file_proto_logstreamer_proto_depIdxs = []int32{
	4, // 0: swiftlog.v1.StreamLogRequest.metadata:type_name -> swiftlog.v1.StreamMetadata
	5, // 1: swiftlog.v1.StreamLogRequest.line:type_name -> swiftlog.v1.LogLine
	2, // 2: swiftlog.v1.StreamLogRequest.completion:type_name -> swiftlog.v1.StreamCompletion
	6, // 3: swiftlog.v1.StreamLogResponse.started:type_name -> swiftlog.v1.StreamStarted
	7, // 4: swiftlog.v1.LogLine.timestamp:type_name -> google.protobuf.Timestamp
	0, // 5: swiftlog.v1.LogLine.level:type_name -> swiftlog.v1.LogLine.Level
	1, // 6: swiftlog.v1.LogStreamer.StreamLog:input_type -> swiftlog.v1.StreamLogRequest
	3, // 7: swiftlog.v1.LogStreamer.StreamLog:output_type -> swiftlog.v1.StreamLogResponse
	7, // [7:8] is the sub-list for method output_type
	6, // [6:7] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_proto_logstreamer_proto_init() }
func file_proto_logstreamer_proto_init() {
	if File_proto_logstreamer_proto != nil {
		return
	}
	file_proto_logstreamer_proto_msgTypes[0].OneofWrappers = []any{
		(*StreamLogRequest_Metadata)(nil),
		(*StreamLogRequest_Line)(nil),
		(*StreamLogRequest_Completion)(nil),
	}
	file_proto_logstreamer_proto_msgTypes[2].OneofWrappers = []any{
		(*StreamLogResponse_Started)(nil),
		(*StreamLogResponse_Error)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_logstreamer_proto_rawDesc), len(file_proto_logstreamer_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_logstreamer_proto_goTypes,
		DependencyIndexes: file_proto_logstreamer_proto_depIdxs,
		EnumInfos:         file_proto_logstreamer_proto_enumTypes,
		MessageInfos:      file_proto_logstreamer_proto_msgTypes,
	}.Build()
	File_proto_logstreamer_proto = out.File
	file_proto_logstreamer_proto_goTypes = nil
	file_proto_logstreamer_proto_depIdxs = nil
}
