run:
  timeout: 5m
  tests: true
  skip-dirs:
    - gen
    - vendor

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - goimports
    - misspell
    - revive
    - gocritic

linters-settings:
  goimports:
    local-prefixes: github.com/aliancn/swiftlog
  revive:
    severity: warning
    rules:
      - name: exported
        severity: warning
      - name: package-comments
        severity: warning
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
