// logstreamer.proto

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v4.25.3
// source: proto/logstreamer.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	LogStreamer_StreamLog_FullMethodName = "/swiftlog.v1.LogStreamer/StreamLog"
)

// LogStreamerClient is the client API for LogStreamer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// LogStreamer service definition
type LogStreamerClient interface {
	// The client calls this method to start a bidirectional stream.
	StreamLog(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[StreamLogRequest, StreamLogResponse], error)
}

type logStreamerClient struct {
	cc grpc.ClientConnInterface
}

func NewLogStreamerClient(cc grpc.ClientConnInterface) LogStreamerClient {
	return &logStreamerClient{cc}
}

func (c *logStreamerClient) StreamLog(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[StreamLogRequest, StreamLogResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &LogStreamer_ServiceDesc.Streams[0], LogStreamer_StreamLog_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamLogRequest, StreamLogResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type LogStreamer_StreamLogClient = grpc.BidiStreamingClient[StreamLogRequest, StreamLogResponse]

// LogStreamerServer is the server API for LogStreamer service.
// All implementations must embed UnimplementedLogStreamerServer
// for forward compatibility.
//
// LogStreamer service definition
type LogStreamerServer interface {
	// The client calls this method to start a bidirectional stream.
	StreamLog(grpc.BidiStreamingServer[StreamLogRequest, StreamLogResponse]) error
	mustEmbedUnimplementedLogStreamerServer()
}

// UnimplementedLogStreamerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLogStreamerServer struct{}

func (UnimplementedLogStreamerServer) StreamLog(grpc.BidiStreamingServer[StreamLogRequest, StreamLogResponse]) error {
	return status.Errorf(codes.Unimplemented, "method StreamLog not implemented")
}
func (UnimplementedLogStreamerServer) mustEmbedUnimplementedLogStreamerServer() {}
func (UnimplementedLogStreamerServer) testEmbeddedByValue()                     {}

// UnsafeLogStreamerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LogStreamerServer will
// result in compilation errors.
type UnsafeLogStreamerServer interface {
	mustEmbedUnimplementedLogStreamerServer()
}

func RegisterLogStreamerServer(s grpc.ServiceRegistrar, srv LogStreamerServer) {
	// If the following call pancis, it indicates UnimplementedLogStreamerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&LogStreamer_ServiceDesc, srv)
}

func _LogStreamer_StreamLog_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(LogStreamerServer).StreamLog(&grpc.GenericServerStream[StreamLogRequest, StreamLogResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type LogStreamer_StreamLogServer = grpc.BidiStreamingServer[StreamLogRequest, StreamLogResponse]

// LogStreamer_ServiceDesc is the grpc.ServiceDesc for LogStreamer service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LogStreamer_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "swiftlog.v1.LogStreamer",
	HandlerType: (*LogStreamerServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamLog",
			Handler:       _LogStreamer_StreamLog_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "proto/logstreamer.proto",
}
