source 'https://rubygems.org'

gem "jekyll", "~> 4.4.1"
gem "webrick"  # required when using Ruby >= 3

gem "just-the-docs", "0.10.1"  # pinned to the current release

# Jekyll plugins
group :jekyll_plugins do
  gem "jekyll-seo-tag"
  gem "jekyll-sitemap"
end